### ISSUE TITLE
Make it clear that RDS Console will call DevOps Guru API calls even not explicitly enabled

### ISSUE THREAD

**Issue by henriquesantanati** [awsdocs/amazon-devops-guru-user-guide#1]
Hello,

From this [document](https://github.com/awsdocs/amazon-devops-guru-user-guide/blob/main/doc_source/working-with-rds.enabling.md) it is not clear that, even if not enabled at all, while access the AWS RDS Console, the Ctrail will log some DevOps Guru API calls.

I've seen these so far: 

[GetResourceCollection](https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_GetResourceCollection.html)
[DescribeEventSourcesConfig](https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_DescribeEventSourcesConfig.html)
[SearchInsights](https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_SearchInsights.html)

I could not see any RDS documentation related to that as well. I think that it would be also good to have some reference around it on RDS Documentation.

**Comment by nijerica** [comment]
Thank you for your feedback on the documentation. We have added the following sentences to this page in the Amazon DevOps Guru User Guide: 
"Amazon RDS makes it easy to discover and enable recommended functionality for an RDS DB instance or DB cluster. To achieve this, RDS makes API calls to other services, such as Amazon EC2, DevOps Guru, and IAM. When the RDS console makes these API calls, AWS CloudTrail logs them for visibility."

You can view the update at https://docs.aws.amazon.com/devops-guru/latest/userguide/working-with-rds.enabling.html.
